# Generated by Django 4.1.7 on 2023-07-26 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.TextField(max_length=255)),
                ('idade', models.IntegerField(max_length=3)),
                ('cpf', models.IntegerField(max_length=11)),
                ('arq', models.FileField(upload_to='img')),
            ],
        ),
    ]
