# Generated by Django 4.1.7 on 2023-07-28 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cadastro_users', '0003_alter_usuario_arq'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='cpf',
            field=models.BigIntegerField(),
        ),
    ]
